[[pages]]
path = "Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "my_pages/explore_data.py"
name = "Data Explorer"
icon = "ğŸ“Š"

[[pages]]
path = "my_pages/model_page.py"
name = "Experiment"
icon = "ğŸ”¬"

[[pages]]
path = "my_pages/saved_model.py"
name = "Saved Experiments"
icon = "ğŸ’¾"