name: Docker Image CI

on:
  push:
    branches:
      -'releases/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/regression:${{ steps.vars.outputs.tag }}
    - name: Push docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/regression:${{ steps.vars.outputs.tag }}
